name: Build and deploy CustomerApi to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_PATH: 'CustomerApi/CustomerApi/CustomerApi.csproj'
  SOLUTION_PATH: 'CustomerApi/CustomerApi.sln'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build solution
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Publish CustomerApi project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: customerapi-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: customerapi-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BF247D574DE242F2A076F56A92B6FA20 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1875E4FC2174E85AFAD640ED27B6319 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F1A9101570B8426F992407515ED83044 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testCustomerApi'
          slot-name: 'Production'
          package: ./publish
